### PR TITLE
feat(downloads): re-implement docx and xlsx downloads in the browser

### PR DESCRIPTION
**Pull request by roedoejet**
remove mat table exporter since it doesn't support our multi-table format

### CODE REVIEW

**Comment by roedoejet** [comment]
This is fairly dense, but I added some comments so hopefully it is follow-able

**Comment by joanise** [comment]
So, since you're working in wordweaver-ui, I assume you've only tested this with fr so far? I wish it was easy to test with both fr and moh, but anyway, I'll review this PR this afternoon.

**Comment by roedoejet** [comment]
> So, since you're working in wordweaver-ui, I assume you've only tested this with fr so far? I wish it was easy to test with both fr and moh, but anyway, I'll review this PR this afternoon.

Correct - I've only tested with `fr`. Yea - something like the deploy preview would be nice.

**Comment by joanise** [comment]
Tested for fr, and it all works nicely. I was taken aback with the download happening as soon as you click the down arrow, but then remembered that's what we said we'd do, and it's a good idea.

About to review the code now.

**Review by joanise — APPROVED** [review]
I didn't analyse to the point of understanding all the code, but it's nicely documented and it looks well designed. We might still review exactly what gets saved in the .docx output, but I think it'll make most sense to do that careful review of the downloaded documents once we have this incorporated into Kawennón:nis itself. The .xlsx is great: no utf8 character corruption!

**Comment by joanise** [comment]
Actually, there is a bug: for French, download .xlsx for a verb asking for all the tenses and all the pronouns, and the imperative is all wrong:
image

**Comment by roedoejet** [comment]
> Actually, there is a bug: for French, download .xlsx for a verb asking for all the tenses and all the pronouns, and the imperative is all wrong: image

is it wrong in the tableviewer too? Like, is it a model problem or a xlsx problem?

**Comment by roedoejet** [comment]
Looks like it's an issue in the model: 
image

**Comment by roedoejet** [comment]
This ought to be fixed for French, but it's not related to the xlsx feature, so I'll merge this in.

**Comment by joanise** [comment]
Good point, if that bug shows up in the table view, it's not related to this PR.

**Pull request merged**
