### PR TITLE
fix: compress .json.gz with zero timestamps for stability

### PR DESCRIPTION
**Pull request by joanise**
tested on Windows (using bash), Linux and MacOS:
 - `cat $file_name | gzip -9 > $file_name.gz` works on Linux and Windows bash, but not MacOS
 - `zero-gzip-timestamp.sh` can work without a temporary file on Windows bash and Linux, but not on MacOS
 - Settled on `zero-gzip-timestamp.sh` using a temporary file, the only solution that worked on all three OSs.

I thought my zero-gzip-timestamp.sh solution with no temporary file was elegant:
```
head -c 4
head -c 4 > /dev/null
printf '\00\00\00\00'
cat
```
the two calls to `head` consume stdin just 4 bytes at a time in Windows Git Bash and Linux, but apparently on MacOS that's not the case, since the output only had 8 bytes and the final `cat` didn't have anything left to read, at least with a small input file.

### CODE REVIEW

**Comment by joanise** [comment]
@roedoejet With this PR, you should be able to run `npm run-script comrpess` on your Mac and then have `git status` show that no files have changed. I have tested that via a dummy repo running CI on macos-latest, but I'd like confirmation that it works on your machine too. Then we can merge here and merge the change into the kawe instance too.

**Comment by roedoejet** [comment]
> @roedoejet With this PR, you should be able to run `npm run-script comrpess` on your Mac and then have `git status` show that no files have changed. I have tested that via a dummy repo running CI on macos-latest, but I'd like confirmation that it works on your machine too. Then we can merge here and merge the change into the kawe instance too.

Hm, unfortunately this just changed the `conjugations.json.gz` file for me. I committed the change here: [ba839e5](https://github.com/roedoejet/wordweaver/pull/79/commits/ba839e54b0c5c13820138785d730931daa6e8462) so you're able to look at the change (and also to test what CI does with it).

**Review by roedoejet — CHANGES_REQUESTED** [review]
> @roedoejet With this PR, you should be able to run `npm run-script comrpess` on your Mac and then have `git status` show that no files have changed. I have tested that via a dummy repo running CI on macos-latest, but I'd like confirmation that it works on your machine too. Then we can merge here and merge the change into the kawe instance too.

Hm, looks good to me, @joanise, but, unfortunately this just changed the `conjugations.json.gz` file for me. I committed the change here: [ba839e5](https://github.com/roedoejet/wordweaver/pull/79/commits/ba839e54b0c5c13820138785d730931daa6e8462) so you're able to look at the change (and also to test what CI does with it).

update: nope, looks like CI failed.

**Comment by joanise** [comment]
Dang, the assumption that gzip output can be considered stable is a faulty one: https://unix.stackexchange.com/questions/570477/gzip-doesnt-produce-the-same-compressed-result-on-macos-vs-linux

FWIW, I discovered I don't need my zero-gzip-timestamp.sh script, all I needed was the `-n` options:
>   -n, --no-name     do not save or restore the original name and timestamp

**Comment by joanise** [comment]
My CI runs on a dummy repo (https://github.com/joanise/just-testing/actions/runs/6931750603) show that macos-latest uses Apple gzip 353.100.22, while ubuntu-latest uses GNU gzip 1.10 and windows-latest with shell: bash uses GNU gzip 1.13.
That SE link I shared above shows similar, and the question and discussion there imply most files will be identical, but not all files.

I think this suggests the following patch to my CI recipe: I should diff the unzipped contents and demand they be the same, not the zipped contents.

I'll still use the -n flag, to reduce unnecessary differences, but it's now clear I cannot prevent all unnecessary differences.

**Comment by joanise** [comment]
Replaced by #81

**Pull request closed without merging**
